[package]
name = "attestation"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10"
base64 = "0.21"
hex = "0.4"
ciborium = "0.2"
x509-parser = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
reqwest = { version = "0.11.27", features = ["json"] }
x509-cert = "0.2"
signature = "2.1"
js-sys = "0.3"

[lib]
crate-type = ["cdylib", "rlib"]
